
package br.com.ecodetech.integracao.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Servicos", targetNamespace = "http://webservices.integracao.ecodetech.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Servicos {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaProdutoXML", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetListaProdutoXML")
    @ResponseWrapper(localName = "getListaProdutoXMLResponse", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetListaProdutoXMLResponse")
    @Action(input = "http://webservices.integracao.ecodetech.com.br/Servicos/getListaProdutoXMLRequest", output = "http://webservices.integracao.ecodetech.com.br/Servicos/getListaProdutoXMLResponse")
    public String getListaProdutoXML();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaClienteXML", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetListaClienteXML")
    @ResponseWrapper(localName = "getListaClienteXMLResponse", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetListaClienteXMLResponse")
    @Action(input = "http://webservices.integracao.ecodetech.com.br/Servicos/getListaClienteXMLRequest", output = "http://webservices.integracao.ecodetech.com.br/Servicos/getListaClienteXMLResponse")
    public String getListaClienteXML();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.ecodetech.integracao.client.Cliente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaCliente", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetListaCliente")
    @ResponseWrapper(localName = "getListaClienteResponse", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetListaClienteResponse")
    @Action(input = "http://webservices.integracao.ecodetech.com.br/Servicos/getListaClienteRequest", output = "http://webservices.integracao.ecodetech.com.br/Servicos/getListaClienteResponse")
    public List<Cliente> getListaCliente();

    /**
     * 
     * @param nomeUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMensagem", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetMensagem")
    @ResponseWrapper(localName = "getMensagemResponse", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetMensagemResponse")
    @Action(input = "http://webservices.integracao.ecodetech.com.br/Servicos/getMensagemRequest", output = "http://webservices.integracao.ecodetech.com.br/Servicos/getMensagemResponse")
    public String getMensagem(
        @WebParam(name = "nomeUsuario", targetNamespace = "")
        String nomeUsuario);

    /**
     * 
     * @param idCliente
     * @return
     *     returns br.com.ecodetech.integracao.client.Cliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCliente", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetCliente")
    @ResponseWrapper(localName = "getClienteResponse", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetClienteResponse")
    @Action(input = "http://webservices.integracao.ecodetech.com.br/Servicos/getClienteRequest", output = "http://webservices.integracao.ecodetech.com.br/Servicos/getClienteResponse")
    public Cliente getCliente(
        @WebParam(name = "idCliente", targetNamespace = "")
        Long idCliente);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.ecodetech.integracao.client.Produto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaProduto", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetListaProduto")
    @ResponseWrapper(localName = "getListaProdutoResponse", targetNamespace = "http://webservices.integracao.ecodetech.com.br/", className = "br.com.ecodetech.integracao.client.GetListaProdutoResponse")
    @Action(input = "http://webservices.integracao.ecodetech.com.br/Servicos/getListaProdutoRequest", output = "http://webservices.integracao.ecodetech.com.br/Servicos/getListaProdutoResponse")
    public List<Produto> getListaProduto();

}
