
package br.com.ecodetech.integracao.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicosService", targetNamespace = "http://utilitarios.integracao.ecodetech.com.br/", wsdlLocation = "http://localhost:8080/integracao/ServicosService?wsdl")
public class ServicosService
    extends Service
{

    private final static URL SERVICOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICOSSERVICE_EXCEPTION;
    private final static QName SERVICOSSERVICE_QNAME = new QName("http://utilitarios.integracao.ecodetech.com.br/", "ServicosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/integracao/ServicosService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICOSSERVICE_WSDL_LOCATION = url;
        SERVICOSSERVICE_EXCEPTION = e;
    }

    public ServicosService() {
        super(__getWsdlLocation(), SERVICOSSERVICE_QNAME);
    }

    public ServicosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICOSSERVICE_QNAME, features);
    }

    public ServicosService(URL wsdlLocation) {
        super(wsdlLocation, SERVICOSSERVICE_QNAME);
    }

    public ServicosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICOSSERVICE_QNAME, features);
    }

    public ServicosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Servicos
     */
    @WebEndpoint(name = "ServicosPort")
    public Servicos getServicosPort() {
        return super.getPort(new QName("http://utilitarios.integracao.ecodetech.com.br/", "ServicosPort"), Servicos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Servicos
     */
    @WebEndpoint(name = "ServicosPort")
    public Servicos getServicosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://utilitarios.integracao.ecodetech.com.br/", "ServicosPort"), Servicos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICOSSERVICE_EXCEPTION!= null) {
            throw SERVICOSSERVICE_EXCEPTION;
        }
        return SERVICOSSERVICE_WSDL_LOCATION;
    }

}
